/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package nursor.org/nursorgate/client */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "export.go"

#include <stdlib.h>
#include <stdbool.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern __declspec(dllexport) void startClient();
extern __declspec(dllexport) void setOutboundToken(char* token);
extern __declspec(dllexport) void setServerHost(char* host);
extern __declspec(dllexport) void exportCaCertToFile(char* certPath);
extern __declspec(dllexport) void setSqlitePath(char* sqlitePath);
extern __declspec(dllexport) char* getDataFromSqlite(char* key);
extern __declspec(dllexport) void setDataToSqlite(char* key, char* value);
extern __declspec(dllexport) void deleteDataFromSqlite(char* key);
extern __declspec(dllexport) void closeSqlite();
extern __declspec(dllexport) char* getToCursorDomain();
extern __declspec(dllexport) char* runGate(char* innerToken);
extern __declspec(dllexport) void setUserInfo(char* innerToken, char* username, char* password);
extern __declspec(dllexport) void setLogWatchMode(_Bool* enableWatch, int* level);
extern __declspec(dllexport) void setCursorGateMode(_Bool* enableCursorGate);
extern __declspec(dllexport) void stopGate();

#ifdef __cplusplus
}
#endif
